### PR TITLE
pedbp

### PR DESCRIPTION
**Pull request by dewittpe**
Submitter checklist:

- [x] My changes follow the guidelines in the `README.md`.
- [x] My changes appear correctly in the preview link (if applicable).

Reviewer checklist:

- [x] The changes follow the guidelines in the `README.md`.
- [x] The changes appear correctly in the preview link (if applicable).

### CODE REVIEW

**Comment by dewittpe** [comment]
Just incase - yes, I'm a member of DBMI: [SOM Profile](https://som.cuanschutz.edu/Profiles/Faculty/Profile/28227)
and the pedbp package was written up in a [news post](https://news.cuanschutz.edu/dbmi/new-tool-provides-global-standard-for-pediatric-blood-pressure-assessment) in December of 2022.

**Comment by vincerubinetti** [comment]
Thanks for submitting this.

To match with the other designs, please take a look at [the image guidelines](https://github.com/CU-DBMI/wall-of-software?tab=readme-ov-file#images), particularly the one about backgrounds. The website and printing process will cut the hexagon shape out for you, so it ideally should not be an inherent part of your image. Like this:
example

To accept your design, we'd need to get rid of that hexagon cut. (Unless you really feel strongly that the hexagon was already an inherent and necessary part of your design, but in your case I don't think it is.)

If you're open to it, here are some more subjective/aesthetic changes to consider:

- Your logo for the website should preferably not have text. In the future, we may have the website show the `name` field for all the entries in a consistent way.
- The content (heart and blood pressure cuff) perhaps goes a little too close to the borders of the hexagon, compared to the other entries. The shapes could be scaled down a bit.
- I think your dark grey background is too dark such that the black text doesn't have enough contrast to be legible for people with low vision. Similarly, the dark red of the heart doesn't contrast well with the dark gray of the blood pressure equipment above it.
- The colors in general look a bit muted/dark and "sterile". Consider using some colors from [this palette](https://tailwindcss.com/docs/customizing-colors). Particularly, I find it often looks better to choose a gray with some hue instead of a "pure" desaturated gray.
- I think getting rid of the heart gradient shadow might also look better.

**Comment by dewittpe** [comment]
@vincerubinetti  - thank you for the input on the image.  I've made some changes and updated this PR.  The example image with the full background was very helpful.

One question and place for some discussion - the use of text on the hexsticker for R packages is common.  See here the set of R package stickers from the [posit store](https://swag.rstudio.com/s/shop).   I'm okay with having a version of the hexsticker without the pedbp name on it for the wall-of-software, but I will also be using a version with the text in other places.  It would be nice to have a consistent logo

**Comment by vincerubinetti** [comment]
Thanks for making that change. Feel free to re-include the text in both images. 

This is all still very new, and we're still working on solidifying the guidelines. But I was careful to say "ideally" no text, and only for the website version. The printed version ideally does contain text. Ultimately, with the wide variety of designs we're going to get, we can't really make strict, 100%-of-the-time rules. 

Fwiw, we were inspired by this site: http://hexb.in, which seems to be half with-text, half no-text. Also keep in mind the wall isn't restricted to R, packages, or any specific language

For now though, asking for both with-text and no-text images hopefully gives us flexibility to pivot later. For example, in the future, we _might_ do something _like_ this with the website to consistently display the name, where text in the image would be redundant and possibly clashing:



Hopefully, most people already have both text versions (e.g. for posters) and non-text versions (e.g. for favicons) of their logo, so and this won't be a big ask.

Re: the screenshot above, another idea I was toying with:

Keep all the website images no-text, so you can admire the aesthetics of the whole wall, just logos. But then when you hover over _any_ cell, _all_ of the cells have their names pop up and their images dimmed, so you can see everything (names and images) at once on inspection.

**Comment by dewittpe** [comment]
The idea and use cases for a text and no-text version of the logo are great, and things I had not thought of.  Since this is a new logo it's easy for me to make multiple versions.  I just reviewed the how the the updated image renders on the page and I want to modify it a bit more - the logo is not centered in the hex image. 

This has been a very useful discussion helping me to not only improve this one logo but others that I'll be working on in the near future.

**Comment by vincerubinetti** [comment]
Regarding your latest commit: Again, it's very important that there be no sign of the hexagon template in the images. Why:

For the website, we might add features or effects that would reveal your hexagon lines. Maybe on hover, the image could morph from a hexagon to a circle. Maybe clicking on the image could open a full screen preview of the software, where we show the logo in _square_ format.

For printing, the cuts they make are not 100% precise, and any printing process will suggest that you to [extend colors beyond the cut lines](https://en.wikipedia.org/wiki/Bleed_(printing)) so you don't get random white/unprinted slivers around the edges.

Also, the overlay you have there is dimming the colors a bit.

**Review by vincerubinetti — APPROVED** [review]

**Comment by vincerubinetti** [comment]
Looks good! Thanks for being the first tester of this process. If you have permissions to merge, feel free to do so when ready, otherwise I'll do it in a bit.

**Comment by dewittpe** [comment]
Thank you @vincerubinetti  - sorry for the error with the hexagon outline.  I had used it to get an idea about how the image might render and forgot to omit it before pushing changes.  Thank you, also, for the feedback on the logo too.  It was helpful to get a better logo.  I'm a better coder than graphic designer.

**Comment by vincerubinetti** [comment]
FYI, I moved that extra image to a new `/variations` folder, where we can keep images that we're not using right now but might use later.

**Pull request merged**
