### PR TITLE
CCC

### PR DESCRIPTION
**Pull request by miltondp**
Submitter checklist:

- [x] My changes follow the guidelines in the `README.md`.
- [x] My changes appear correctly in the preview link (if applicable).

Reviewer checklist:

- [x] The changes follow the guidelines in the `README.md`.
- [x] The changes appear correctly in the preview link (if applicable).

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Looks like you have a little cutoff here, and it's not quite centered:

image

Also, is the background intended to match the background of the website, or is that just a coincidence? Because the background of the website is subject to change. Consider if you want to make the outside of the shape just transparent. We can print it as transparent if you want.

Also perhaps you want to include the full name (with "clustermatch") in the name or description?

**Comment by miltondp** [comment]
Ah, nice catch! I forgot to push the latest logo version. I never intended to match the logo background with the website's. I generated the logo with DALLE, so it's a bit hard for me to modify the background. I'm fine with it if that's ok. I also changed the description to "Clustermatch Correlation Coefficient"

I pushed the changes, but now the logo does not show in the preview. Why is that?

**Comment by vincerubinetti** [comment]
The image name must be a kebab-case of the project name; that's where the page looks for the image, so that's why it wasn't showing. I fixed that.

Please also take a look at the images I replaced. I was going to redo them by hand in SVG but that turned out to be taking more time than I could afford at the moment. Instead, I just resized them properly and consistently (/images and /print versions should basically be the same positioning and cropping), and made the background transparent.

I had to scale up the /print version because I didn't have it in higher resolution. If you have an original, high resolution version of the logo from Dall E, please drop it in a comment below.

**Comment by miltondp** [comment]
> The image name must be a kebab-case of the project name; that's where the page looks for the image, so that's why it wasn't showing. I fixed that.

Ah, of course! Thank you.

> Please also take a look at the images I replaced. I was going to redo them by hand in SVG but that turned out to be taking more time than I could afford at the moment. Instead, I just resized them properly and consistently (/images and /print versions should basically be the same positioning and cropping), and made the background transparent.

They look great!

> I had to scale up the /print version because I didn't have it in higher resolution. If you have an original, high resolution version of the logo from Dall E, please drop it in a comment below.

Thank you so much, Vince. I think this looks really good.

**Comment by vincerubinetti** [comment]
I used a program called Vector Magic to vectorize the image, then Adobe Illustrator to clean it up slightly. See the attached source SVG and high-res PNG files. Please keep them in your repo for your later use.

[clustermatch-correlation-coefficient.zip](https://github.com/CU-DBMI/wall-of-software/files/14249941/clustermatch-correlation-coefficient.zip)

**Review by vincerubinetti — APPROVED** [review]

**Comment by miltondp** [comment]
Wow, amazing, @vincerubinetti, thank you so much for this!

**Pull request merged**
