### PR TITLE
Hendricks Lab, PATH-GDS

### PR DESCRIPTION
**Pull request by wolffha**
Added Hendricks lab and PATH-GDS to the groups - Hopefully all image files are the correct and intended size.

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Did you check "Allow edits by maintainers" per the [readme](https://github.com/CU-DBMI/wall-of-software?tab=readme-ov-file#process)?

**Comment by vincerubinetti** [comment]
Never mind, I just realized you won't be able to do that. Let me make some changes to the repo.

**Comment by vincerubinetti** [comment]
@wolffha Please remove the hexagon border and extend the background per the readme:
https://github.com/CU-DBMI/wall-of-software?tab=readme-ov-file#images

**Comment by wolffha** [comment]
Image files updated

**Comment by vincerubinetti** [comment]
Thanks, looks good.

**Pull request merged**
