### PR TITLE
Zhang Lab

### PR DESCRIPTION
**Pull request by reyvnth**
Submitter checklist:

- [x] My changes follow the guidelines in the `README.md`.
- [x] My changes appear correctly in the preview link (if applicable).

Reviewer checklist:

- [ ] The changes follow the guidelines in the `README.md`.
- [ ] The changes appear correctly in the preview link (if applicable).

### CODE REVIEW

**Comment by vincerubinetti** [comment]
I would crop it a bit further even, leaving even more white space around it, like the Greene Lab logo. It's also a bit off center. Also see the _template.png.

**Comment by vincerubinetti** [comment]
I would also consider adding a description for the lab, if it has one. The [Greene Lab](https://greenelab.com/) informally has a "Where data and biology meet" tag line, which I plan to add to the wall soon.

**Comment by reyvnth** [comment]
Yes, I realized that logo dimensions were not aligned after submitting the pull request and on viewing the preview. So, I made another commit with an updated logo which looks better. I will add the description soon.

Thanks,
Revanth

From: Vincent Rubinetti ***@***.***>
Date: Monday, February 12, 2024 at 11:25 AM
To: CU-DBMI/wall-of-software ***@***.***>
Cc: Krishna, Revanth ***@***.***>, Author ***@***.***>
Subject: Re: [CU-DBMI/wall-of-software] Zhang Lab (PR #9)
[External Email - Use Caution]

I would crop it a bit further even, leaving even more white space around it, like the Greene Lab logo. Also see the _template.png.

**Comment by vincerubinetti** [comment]
Yes, I saw you downsized the image in a second commit, but it is still off center and still probably needs a bit more white space around it.

**Comment by reyvnth** [comment]
Hi Vincent,

I have uploaded the new logo. Please let me know if that’s fine. And Sorry for the delay.

Best,
Revanth

From: Vincent Rubinetti ***@***.***>
Date: Monday, February 12, 2024 at 11:47 AM
To: CU-DBMI/wall-of-software ***@***.***>
Cc: Krishna, Revanth ***@***.***>, Author ***@***.***>
Subject: Re: [CU-DBMI/wall-of-software] Zhang Lab (PR #9)
[External Email - Use Caution]

Yes, I saw you downsized the image in a second commit, but it is still off center and still probably needs a bit more white space around it.

**Comment by vincerubinetti** [comment]
It was still off center, I've fixed it for you:
 → 

In the future, please use the _template.png and Netlify preview link to visually check your images.

**Comment by vincerubinetti** [comment]
https://github.com/CU-DBMI/wall-of-software/pull/10

**Pull request closed without merging**
